# Generated by Django 3.1.7 on 2021-03-21 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210321_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='score',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.score'),
        ),
    ]
